# Generated by Django 5.2.13 on 2026-04-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('OCM', 'OCM'), ('NITI', 'NITI'), ('LOCAL', 'LOCAL')], default='LOCAL', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='station_external_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
