# Generated by Django 5.2.13 on 2026-04-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('total_slots', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('charger_types', models.JSONField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
